# Generated by Django 2.2.2 on 2019-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
